import Head from 'next/head'

const IndexPage = () => {
    return (
        <Head>
            <title>NFT Launch Kit</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default IndexPage